version: "3.8"
services:
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8090:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
